[tool.poetry]
name = "prod_fastapi_demo"
version = "0.1.0"
description = "A demo of a production-ready project based on GINO and FastAPI."
authors = ["Aobo Shi <aobo.shi@decentfox.com>"]

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "*"
gino = { git = "https://github.com/python-gino/gino.git" }
gino-starlette = { git = "https://github.com/python-gino/gino-starlette.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
